# Модуль 1: Основы PyTorch

## Теория

**Тензор** — применяемый в математике и физике математический объект линейной алгебры, заданный на векторном пространстве конечной размерности.  
  
**Размерность тензора** - это количество его осей (ранг). Например:
1. 0D тензор - скаляр. Имеет 0 осей.
1. 1D тензор - вектор-строка или вектор-столбец. Имеет одну ось (ранг).
2. 2D тензор - матрица. Имеет 2 оси (ранг 0 - направление по x (столбцам), ранг 1 - направление по y (строкам))

## Задачи

In [1]:
import torch

### Создание тензоров:

1. Создай 1D тензор размером 10, содержащий случайные числа от 0 до 1.
2. Создай 2D тензор размером 3x4, заполненный нулями.
3. Создай 3D тензор размером 2x3x4, заполненный единицами.
4. Создай тензор, содержащий числа от 1 до 20 и имеющий размерность 4x5.

In [129]:
# Решение задачи №1
t = torch.rand(10)
print(t)
print(t.shape)

tensor([0.6678, 0.8196, 0.4763, 0.3487, 0.8138, 0.3911, 0.7451, 0.5084, 0.2250,
        0.2908])
torch.Size([10])


In [130]:
# Решение задачи №2
t = torch.zeros((3, 4))
print(t)
print(t.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])


In [ ]:
# Решение задачи №3
t = torch.ones((2, 3, 4))
print(t)
print(t.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 3, 4])


In [135]:
# Решение задачи №4
t = torch.arange(1, 21).reshape((4, 5))
print(t)
print(t.shape)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
torch.Size([4, 5])


### Операции с тензорами:

1. Создай два 2D тензора (размером 2x3) и выполни операции сложения, вычитания и умножения поэлементно.
2. Создай 1D тензор размером 5 и возведи его элементы в квадрат (используй векторизованные операции).
3. Измени форму 1D тензора размером 12 в 2D тензор размером 3x4.

In [ ]:
# Решение задачи №1: Создай два 2D тензора (размером 2x3) и выполни операции сложения, вычитания и умножения поэлементно

t1 = torch.arange(1, 7).reshape(2, 3)
t2 = torch.arange(7, 13).reshape(2, 3)

print("Исходные тензоры:")
print(f"Тензор 1:\n{t1}")
print(f"Тензор 2:\n{t2}")

print("=" * 100)


print("Поэлементное сложение:")
print(t1 + t2)
print("Поэлементное вычитание:")
print(t1 - t2)
print("Поэлементное умножение:")
print(t1 * t2)
print(f"Поэлементное деление:")
print(t1 / t2)

Исходные тензоры:
Тензор 1:
tensor([[1, 2, 3],
        [4, 5, 6]])
Тензор 2:
tensor([[ 7,  8,  9],
        [10, 11, 12]])
Поэлементное сложение:
tensor([[ 8, 10, 12],
        [14, 16, 18]])
Поэлементное вычитание:
tensor([[-6, -6, -6],
        [-6, -6, -6]])
Поэлементное умножение:
tensor([[ 7, 16, 27],
        [40, 55, 72]])
Поэлементное деление:
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])


In [ ]:
# Решение задачи №2: Создай 1D тензор размером 5 и возведи его элементы в квадрат (используй векторизованные операции).
t = torch.arange(1, 6)

print(f"Способ 1:\n{t ** 2}")
print(f"Способ 2:\n{t.square()}")


Способ 1:
tensor([ 1,  4,  9, 16, 25])
Способ 2:
tensor([ 1,  4,  9, 16, 25])


In [151]:
# Решение задачи №3: Измени форму 1D тензора размером 12 в 2D тензор размером 3x4.
t = torch.arange(1, 13)
print(f"Исходный тензор:\n{t}")
print(f"Новый:\n{t.reshape((3, 4))}")

Исходный тензор:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
Новый:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


### Выбор и индексация:

1. Создай 2D тензор размером 4x4 и выбери первый и третий столбцы.
2. Извлеки подмассив из 2D тензора размером 3x3, начиная с 1-й строки и 1-го столбца.
3. Используя маску, выбери из 1D тензора все значения, которые больше 0.5.

In [154]:
# Решение задачи №1: Создай 2D тензор размером 4x4 и выбери первый и третий столбцы.
t = torch.arange(1, 17).reshape((4, 4))

print(f"Исходный тензор:\n{t}")

print(f"Только выбранные столбцы:\n{t[:, [0, 2]]}")

Исходный тензор:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
Только выбранные столбцы:
tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15]])


In [168]:
# Решение задачи №2: Извлеки подмассив из 2D тензора размером 3x3, начиная с 1-й строки и 1-го столбца.
t = torch.arange(1, 13).reshape((4, 3))

print(f"Исходный тензор:\n{t}")

print(f"Извлеченный подмассив:\n{t[0:3]}")
print(f"Способ №2:\n{t[[0, 2, 3], :]}")

Исходный тензор:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
Извлеченный подмассив:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Способ №2:
tensor([[ 1,  2,  3],
        [ 7,  8,  9],
        [10, 11, 12]])


In [172]:
# Решение задачи №3: Используя маску, выбери из 1D тензора все значения, которые больше 0.5.
t = torch.rand(10)
mask = t.ge(0.5)

print(f"Исходный тензор:\n{t}")
print(f"Новый:\n{torch.masked_select(t, mask)}")

Исходный тензор:
tensor([0.3194, 0.2168, 0.6116, 0.2252, 0.5611, 0.1919, 0.6170, 0.2343, 0.7929,
        0.0492])
Новый:
tensor([0.6116, 0.5611, 0.6170, 0.7929])


### Агрегация:

1. Создай 2D тензор размером 5x5 и вычисли сумму элементов по строкам и столбцам.
2. Найди максимальное значение и его индекс в 1D тензоре.
3. Вычисли среднее значение всех элементов в 3D тензоре.

In [182]:
# Решение задачи №1: Создай 2D тензор размером 5x5 и вычисли сумму элементов по строкам и столбцам.
t = torch.arange(1, 26).reshape((5, 5))

print(f"Исходный тензор:\n{t}")

print(f"Сумма по столбцам: {t.sum(0)}")
print(f"Сумма по строкам: {t.sum(1)}")

Исходный тензор:
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])
Сумма по столбцам: tensor([55, 60, 65, 70, 75])
Сумма по строкам: tensor([ 15,  40,  65,  90, 115])


In [191]:
# Решение задачи №2: Найди максимальное значение и его индекс в 1D тензоре.
t = torch.tensor([10, -2, 15, 0, 12])

print(f"Исходный тензор:\n{t}")
ans = t.max(0)
print(f"Максимальное значение в тензоре и индекс: {int(ans.values)}, {int(ans.indices)}")

Исходный тензор:
tensor([10, -2, 15,  0, 12])
Максимальное значение в тензоре и индекс: 15, 2


In [ ]:
# Функция max() для 2D тензора
t = torch.tensor([[10, 2, 15], [-20, -1, -15]])

print(f"Макс. значение по строкам:\n{t.max(1)}")
print()
print(f"Макс. значение по столбцам:\n{t.max(0)}")

Макс. значение по строкам:
torch.return_types.max(
values=tensor([15, -1]),
indices=tensor([2, 1]))

Макс. значение по столбцам:
torch.return_types.max(
values=tensor([10,  2, 15]),
indices=tensor([0, 0, 0]))


In [208]:
# Решение задачи №3: Вычисли среднее значение всех элементов в 3D тензоре.
t = torch.arange(1, 11).reshape((2, 5))

print(f"Исходный тензор:\n{t}")

print(f"Среднее значение тензора: {t.mean(dtype=torch.float16)}")

Исходный тензор:
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
Среднее значение тензора: 5.5


### Дополнительные задачи:

Умножение матрицы на вектор:
1. Создай 2D тензор размерности 3x4 и 1D тензор размерности 4, затем перемножь их.
  
Транспонирование:
1. Создай 2D тензор размером 3x2 и транспонируй его.
  
Сложные операции:
1. Создай 2D тензор размером 3x3 и найди его обратную матрицу (если это возможно).
2. Создай тензор, представляющий случайную выборку из нормального распределения (например, размер 100x2) и вычисли средние значения по столбцам.

In [212]:
# Умножение матрицы на вектор: Создай 2D тензор размерности 3x4 и 1D тензор размерности 4, затем перемножь их.
t1 = torch.arange(1, 13).reshape((3, 4))
t2 = torch.arange(1, 5)

print(f"Умножение матрицы 3х4 на вектор 4х1")
print(f"Ответ:\n{t1@t2}")

Умножение матрицы 3х4 на вектор 4х1
Ответ:
tensor([ 30,  70, 110])


In [213]:
# Транспонирование: Создай 2D тензор размером 3x2 и транспонируй его.
t = torch.arange(1, 7).reshape((3, 2))

print(f"Исходный тензор:\n{t}")
print(f"После транспонирования:\n{t.t()}")

Исходный тензор:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
После транспонирования:
tensor([[1, 3, 5],
        [2, 4, 6]])


In [240]:
# Сложные операции: Создай 2D тензор размером 3x3 и найди его обратную матрицу (если это возможно).
t = torch.randn(1, 2, 2)

print(f"Исходный тензор:\n{t}")
inv_mat = t.inverse()
print(f"Обратная матрица:\n{inv_mat}")
print()
print(f"Проверка что все корректно рассчитано\nДолжна получиться единичная матрица:\n{torch.round(inv_mat @ t)}")

print("Все корректно работает!")

Исходный тензор:
tensor([[[-0.9644,  1.9868],
         [ 1.2749,  1.0401]]])
Обратная матрица:
tensor([[[-0.2941,  0.5619],
         [ 0.3605,  0.2727]]])

Проверка что все корректно рассчитано
Должна получиться единичная матрица:
tensor([[[1., -0.],
         [0., 1.]]])
Все корректно работает!


In [248]:
# Сложные операции: Создай тензор, представляющий случайную выборку из нормального распределения (например, размер 100x2) и вычисли средние значения по столбцам.
t = torch.normal(2, 3, (100, 2))

print(f"Исходный тензор:\n{t}")

print(f"Средние значения по столбцам:\n{t.mean(0)}")

Исходный тензор:
tensor([[ 1.7072, -2.4821],
        [-3.9435, -1.0811],
        [ 1.3055,  2.9678],
        [ 0.2584, -4.2425],
        [ 3.1692,  5.8541],
        [ 4.8143,  1.2522],
        [ 3.8322, -0.6353],
        [ 2.9752, -2.0034],
        [ 0.9330,  2.4602],
        [ 4.4398,  1.4002],
        [-2.2214, -2.7087],
        [ 2.2480, -0.3102],
        [ 4.0257, -0.9584],
        [-4.2845,  6.7111],
        [-3.6460,  6.9294],
        [-0.0187, -0.4226],
        [ 1.8331,  2.3063],
        [ 0.1986, -1.3929],
        [ 4.3550,  2.6365],
        [-0.8984,  1.4387],
        [ 1.4080,  1.9245],
        [ 3.7517,  1.9415],
        [ 1.4583,  4.7711],
        [-0.1230,  0.8329],
        [10.5156, -0.3677],
        [-2.9869, -0.7502],
        [ 3.4821,  0.7936],
        [ 1.8214,  1.2421],
        [-4.6821,  0.5781],
        [ 4.3679, -4.6710],
        [-3.9969,  4.6467],
        [ 2.7379, -0.7176],
        [ 5.7924,  3.4198],
        [ 8.4806,  5.6090],
        [ 4.3994,  3.6213],
   